apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: train-service
  template:
    metadata:
      labels:
        app: train-service
    spec:
      containers:
        - name: train-service
          image: naza1re/train-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_RR_URL
              valueFrom:
                configMapKeyRef:
                  name: train-service-config
                  key: DB_RR_URL
            - name: DB_RR_USER
              valueFrom:
                secretKeyRef:
                  name: train-service-secrets
                  key: DB_RR_USER
            - name: DB_RR_PASS
              valueFrom:
                secretKeyRef:
                  name: train-service-secrets
                  key: DB_RR_PASS
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: train-service-config
                  key: SERVER_PORT
