name: Run Kotlin Tests

on:
  push:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin

      - name: Configure Docker to use Google Container Registry
        run: |
          gcloud auth configure-docker

      - name: Get Git commit SHA
        id: commit_sha
        run: |
          echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV



      - name: Build Docker image for train-service
        run: |
          docker build --no-cache -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/train-service:${{ env.COMMIT_SHA }} ./train-service

      - name: Build Docker image for ticket-service
        run: |
          docker build --no-cache -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/ticket-service:${{ env.COMMIT_SHA }} ./ticket-service



      - name: Push Docker image of train-service
        run: |
          docker tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/train-service:${{ env.COMMIT_SHA }} gcr.io/${{ secrets.GCP_PROJECT_ID }}/train-service:latest
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/train-service:latest

      - name: Push latest tag for ticket-service
        run: |
          docker tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/ticket-service:${{ env.COMMIT_SHA }} gcr.io/${{ secrets.GCP_PROJECT_ID }}/ticket-service:latest
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/ticket-service:latest
      
      

      - name: Set up GKE credentials
        run: |
          gcloud container clusters get-credentials rail-reserve-claster \
          --region us-central1 \
          --project rail-reserve-458815

      - name: Apply common Kubernetes resources
        run: |
          kubectl apply -f k8s/common/postgres-deployment.yaml
          kubectl apply -f k8s/common/postgres-service.yaml
          kubectl apply -f k8s/common/configmap.yaml
          kubectl apply -f k8s/common/secret.yaml


      - name: Deploy train-service
        run: |
          kubectl apply -f k8s/train-service/train-service-deployment.yaml
          kubectl apply -f k8s/train-service/train-service-service.yaml
          kubectl set image deployment/train-service train-service=gcr.io/${{ secrets.GCP_PROJECT_ID }}/train-service:${{ env.COMMIT_SHA }}
          

      - name: Deploy ticket-service
        run: |
          kubectl apply -f k8s/ticket-service/ticket-service-deployment.yaml
          kubectl apply -f k8s/ticket-service/ticket-service-service.yaml
          kubectl set image deployment/ticket-service ticket-service=gcr.io/${{ secrets.GCP_PROJECT_ID }}/ticket-service:${{ env.COMMIT_SHA }}

